### ISSUE TITLE
[Bug] Unable to use WandbLogger

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/Trainer#19]
### Describe the bug

I tried using the WandB logger for training in the TTS repo, but it didn't work.

### To Reproduce

- Clone TTS repo
- Modify the LJSpeech recipe's dataset path
- Run:

```bash
CUDA_VISIBLE_DEVICES=0 python recipes/ljspeech/vits_tts/train_vits.py \
    --coqpit.dashboard_logger wandb \
    --coqpit.project_name FakeName \
    --coqpit.wandb_entity FakeEntity \
```

It crashes with this error:

```
Traceback (most recent call last):
  File "runs/train_vits.py", line 85, in <module>
    eval_samples=eval_samples,
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 359, in __init__
    self.dashboard_logger = logger_factory(config, output_path)
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/logging/__init__.py", line 36, in logger_factory
    entity=config.wandb_entity,
TypeError: Can't instantiate abstract class WandbLogger with abstract methods add_audio, add_figure, add_scalar
```

### Expected behavior

It should work just like the default Tensorboard logger

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.2",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.11",
        "version": "#202202230823 SMP PREEMPT Wed Feb 23 14:53:24 UTC 2022"
    }
}
```

**Comment by shigabeev** [comment]
Did you find a solution?

**Comment by erogol** [comment]
There are missing functions in the WB class that needs to be implemented for the fix.
