### ISSUE TITLE
[Bug] No warning or error when no eval samples provided 

### ISSUE THREAD

**Issue by erogol** [coqui-ai/Trainer#23]
### Describe the bug

👟 needs to raise an error when there is no eval sample or skip the eval step.

👉 https://github.com/coqui-ai/TTS/issues/1447 

### To Reproduce

https://github.com/coqui-ai/TTS/issues/1447

### Expected behavior

Raise an error " [!] No eval samples provided" 

Or skip the eval step

### Environment

```shell
https://github.com/coqui-ai/TTS/issues/1447
```

**Comment by WeberJulian** [comment]
It should probably crash and if people want to train without eval samples, they can skip it with `run_eval = False`

**Comment by WeberJulian** [comment]
Not sure where to raise the error though.

If we put it in the `__init__` [here](https://github.com/coqui-ai/Trainer/blob/45a5604cc23dba2ecebf2879d2e1dcc1be64ac38/trainer/trainer.py#L428), we risk raising an error when the samples were actually being loaded in `model.get_data_loader()`.

But if we check after the get_eval_dataloader [here](https://github.com/coqui-ai/Trainer/blob/45a5604cc23dba2ecebf2879d2e1dcc1be64ac38/trainer/trainer.py#L1208), when no eval sample are provided it can crash if the `model.get_data_loader` doesn't support no samples being passed to it.
For example gan dataset here throws this without eval samples.

```
Traceback (most recent call last):
  File "/home/julian/workspace/Trainer/trainer/trainer.py", line 1467, in fit
    self._fit()
  File "/home/julian/workspace/Trainer/trainer/trainer.py", line 1453, in _fit
    self.eval_epoch()
  File "/home/julian/workspace/Trainer/trainer/trainer.py", line 1314, in eval_epoch
    self.get_eval_dataloader(
  File "/home/julian/workspace/Trainer/trainer/trainer.py", line 777, in get_eval_dataloader
    return self._get_loader(
  File "/home/julian/workspace/Trainer/trainer/trainer.py", line 700, in _get_loader
    loader = model.get_data_loader(
  File "/home/julian/workspace/TTS/TTS/vocoder/models/gan.py", line 333, in get_data_loader
    dataset = GANDataset(
  File "/home/julian/workspace/TTS/TTS/vocoder/datasets/gan_dataset.py", line 36, in __init__
    self.compute_feat = not isinstance(items[0], (tuple, list))
TypeError: 'NoneType' object is not subscriptable
```
Where should we do this in your mind @erogol ?

**Comment by erogol** [comment]
maybe we can use an empty list as the default for the samples and check the data loader size. If it is zero, raise an error.

**Comment by WeberJulian** [comment]
We'd still have the same problem, since item[0] would raise out if range right?
