### ISSUE TITLE
[Bug] data = [self.dataset[idx] for idx in possibly_batched_index] TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ikcla** [coqui-ai/Trainer#68]
### Describe the bug

possibly_batched_index is not a list. 

### To Reproduce

python -m trainer.distribute --gpus "0,1" --script train_multi.py --restore_path /root/.local/share/tts/tts_models--en--ljspeech--vits/model_file.pth

### Logs

```shell
> TRAINING (2022-08-26 01:41:21)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/trainer/trainer.py", line 1533, in fit
    self._fit()
  File "/opt/conda/lib/python3.7/site-packages/trainer/trainer.py", line 1517, in _fit
    self.train_epoch()
  File "/opt/conda/lib/python3.7/site-packages/trainer/trainer.py", line 1281, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
TypeError: 'int' object is not iterable

 ! Run is kept in logs/multi_be/vits_ljs_speaker_embedded-August-26-2022_01+41AM-0000000
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/trainer/trainer.py", line 1533, in fit
    self._fit()
  File "/opt/conda/lib/python3.7/site-packages/trainer/trainer.py", line 1517, in _fit
    self.train_epoch()
  File "/opt/conda/lib/python3.7/site-packages/trainer/trainer.py", line 1281, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
TypeError: 'int' object is not iterable
```

### Environment

```shell
docker pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
```

**Comment by erogol** [comment]
It is not about 👟

**Comment by ikcla** [comment]
Do you have any pointer for the issue? I uninstall and install Trainer from your git repo. Tested on single GPU and it worked fine. The problem only occured when using trainer.
